---
title: "Socc 19 eval"
output:
  pdf_document:
    keep_tex: true
---

```{r rawpb_cmp, fig.width=7, fig.height=5}
# Metrics:
# RuntimeReadyTime -> time between the start of the function and until it is ready to start serving requests.
# ExecID -> Treatment replica ID
# ReqID -> ID of the request within the treatment replica (0 meaning the first request)

require(dplyr)
require(ggplot2)
require(ggpubr)
library(boot)

# Reading data
read_startup <- function(f) {
  df <- read.csv(f) 
  df <- df %>% filter(Metric == "RuntimeReadyTime" & ReqID == 0) %>% select(App, Value_NS)
  colnames(df) <- c("app", "value")
  df$value <- df$value / 10^6 
  df <- df %>% mutate(app = ifelse(app == "NoOp", "NOOP", "Thumbnail Maker"))
  return(df)
}

pb <- read_startup("criu_nobpftrace_nogc_nowarmup.csv")
pb$type <- "Prebaking"
vanilla <- read_startup("nocriu_nobpftrace_nogc_nowarmup.csv")
vanilla$type <- "Vanilla"

pb_noop <- pb %>% filter(app == "NOOP")
vanilla_noop <- vanilla %>% filter(app == "NOOP")
pb_thumb <- pb %>% filter(app == "Thumbnail Maker")
vanilla_thumb <- vanilla %>% filter(app == "Thumbnail Maker")

shapiro.test(pb_noop$value)
shapiro.test(vanilla_noop$value)
wilcox.test(vanilla_noop$value, pb_noop$value, conf.int = T)
shapiro.test(pb_thumb$value)
shapiro.test(vanilla_thumb$value)
wilcox.test(vanilla_thumb$value, pb_thumb$value, conf.int = T)

# Some samples did not pass the Shapiro test, so let's calculate
# the confidence interval using bootstrap and test using a non-parametric
# test.

# Calculate confidence intervals around the mean.
# Inspiration: https://rpubs.com/dgolicher/median_boot
median_cl_boot <- function(x, conf = 0.95) {
    lconf <- (1 - conf)/2
    uconf <- 1 - lconf
    require(boot)
    bmedian <- function(x, ind) median(x[ind])
    bt <- boot(x, bmedian, 1000)
    bb <- boot.ci(bt, type = "perc")
    data.frame(y = median(x), ymin = quantile(bt$t, lconf), ymax = quantile(bt$t, 
        uconf))
}

median_ci_text <- function(x, conf = 0.95) {
    lconf <- (1 - conf)/2
    uconf <- 1 - lconf
    require(boot)
    bmedian <- function(x, ind) median(x[ind])
    bt <- boot(x, bmedian, 1000)
    bb <- boot.ci(bt, type = "perc")
    data.frame(y = max(x) + 12,
               label = paste('Median=[', signif(quantile(bt$t, lconf), 2), ', ', signif(quantile(bt$t, uconf), 2),']', sep=""))
}

# Graphing
p <- c("yellowgreen", "violetred4")  # from viridis color pallete.
cOff <- p[1]
cOn <- p[2]
ggplot(rbind(pb, vanilla), aes(type, value, color=type)) +
  geom_jitter(alpha=0.1) +
  stat_summary(fun.data = median_cl_boot, geom = "errorbar") +
  stat_summary(fun.data = median_ci_text, geom = "text", size=3.5)  +
  facet_wrap(~app) +
  theme_pubclean() +
  scale_color_manual(values=p) +
  scale_y_continuous(limits = c(0, max(vanilla$value)+20), breaks = seq(0, max(vanilla$value), by = 50)) +
  labs(x="Technique", y="Startup time (ms)")+
  theme(
    legend.position="none",
    axis.title.x=element_blank(),
    panel.grid.major.y = element_line(colour = "darkgray", linetype = 3))

ggsave("startup_cmp_nowarmup.png")
```

```{r bpfstrace_cmp, fig.width=7, fig.height=5}
# Metrics:
# InitializationTime -> time between the exec of the function and until it is ready to start serving requests.
# ExecID -> Treatment replica ID
# ReqID -> ID of the request within the treatment replica (0 meaning the first request)
require(dplyr)
require(ggplot2)
require(ggpubr)


read_startup_bpfstrace <- function(f) {
  df <- read.csv(f) 
  df <- df %>% filter(ReqID == 0) %>% select(App, Metric, Value_NS)
  colnames(df) <- c("app", "metric", "value")
  df$value <- df$value / 10^6
  df <- df %>% mutate(app = ifelse(app == "NoOp", "NOOP", "Thumbnail Maker"))

  SAMPLE_SIZE <- 200
  ct <- df %>% filter(metric == "CloneTime") %>% select(app, metric, value) %>% sample_n(SAMPLE_SIZE)
  ct$metric <- "CLONE"
  et <- df %>% filter(metric == "ExecTime") %>% select(app, metric, value) %>% sample_n(SAMPLE_SIZE)
  et$metric <- "EXEC"
  it <- df %>% filter(metric == "InitializationTime") %>% select(app, metric, value) %>% sample_n(SAMPLE_SIZE)
  it$metric <- "APPINIT"
  rt <- df %>% filter(metric == "RuntimeTime")
  if (NROW(rt) > 0) {
    rt <- rt %>% select(app, metric, value) %>% sample_n(SAMPLE_SIZE)
  } else {
    # The prebaking output CSV has no RuntimeTime entries. It should be 0.
    # Ensuring that all dfs have the same size.  
    rt <- rbind(
    data.frame("app"=replicate(SAMPLE_SIZE, "NOOP"), "value"=replicate(SAMPLE_SIZE, 0), "metric"=replicate(SAMPLE_SIZE, "0")),
    data.frame("app"=replicate(SAMPLE_SIZE, "Thumbnail Maker"), "value"=replicate(SAMPLE_SIZE, 0), "metric"=replicate(SAMPLE_SIZE, "0")))
  }
  rt$metric <- "RTS"
  return(rbind(ct, et, rt, it))
}

pb <- read_startup_bpfstrace("criu_bpftrace_nogc_nowarmup.csv")
vanilla <- read_startup_bpfstrace("nocriu_bpftrace_nogc_nowarmup.csv")

calc_perc <- function(df, appName){
  df %>%
    filter(app==appName) %>%
    group_by(metric) %>%
    summarise(sum=sum(value)) %>%
    mutate(perc=signif((sum/sum(sum))*100, digits=3))
}

noop_pb_perc <- calc_perc(pb, "NOOP")
noop_pb_perc$app = "NOOP"
noop_pb_perc$type = "Prebaking"

noop_v_perc <- calc_perc(vanilla, "NOOP")
noop_v_perc$app = "NOOP"
noop_v_perc$type = "Vanilla"

tm_pb_perc <- calc_perc(pb, "Thumbnail Maker")
tm_pb_perc$app = "Thumbnail Maker"
tm_pb_perc$type = "Prebaking"

tm_v_perc <- calc_perc(vanilla, "Thumbnail Maker")
tm_v_perc$app = "Thumbnail Maker"
tm_v_perc$type = "Vanilla"

p <- c("yellowgreen", "violetred4")  # from viridis color pallete.
cOff <- p[1]
cOn <- p[2]
ggplot(rbind(noop_pb_perc, noop_v_perc, tm_pb_perc, tm_v_perc), aes(fill=type, y=perc, x=metric)) +
  facet_wrap(~app) +
  geom_col(position=position_dodge2(), color = "black", size=0.2, alpha=0.9) +
  geom_text(aes(label=paste(perc, "%", sep=""), y=perc+2), position = position_dodge(width=1), size=3, hjust = 0)+
  labs(x="Startup Component", y="Percentage of the Startup Time (%)", fill="Technique:")+
  scale_fill_manual(values=p) +
  scale_x_discrete(limits=c("APPINIT","RTS", "EXEC", "CLONE")) +
  scale_y_continuous(limits=c(0,110), breaks = seq(0, 110, 20)) +
  coord_flip() +
  theme_pubclean() +
  theme(
    panel.grid.major.y = element_line(colour = "darkgray", linetype = 3))

ggsave("startup_components.png")
```

```{r service_time_cmp, fig.width=7, fig.height=5}
# Metrics:
# RuntimeReadyTime -> time between the start of the function and until it is ready to start serving requests.
# ExecID -> Treatment replica ID
# ReqID -> ID of the request within the treatment replica (0 meaning the first request)

require(dplyr)
require(ggplot2)
require(ggpubr)

# Reading data
read_service_time <- function(f) {
  df <- read.csv(f) 
  df <- df %>% filter(Metric == "ServiceTime") %>% select(App, Value_NS)
  colnames(df) <- c("app", "value")
  df$value <- df$value / 10^6 
  df <- df %>% mutate(app = ifelse(app == "NoOp", "NOOP", "Thumbnail Maker"))
  return(df)
}

pb <- read_service_time("criu_nobpftrace_nogc_nowarmup.csv")
pb$type <- "Prebaking"
vanilla <- read_service_time("nocriu_nobpftrace_nogc_nowarmup.csv")
vanilla$type <- "Vanilla"

pb_noop <- pb %>% filter(app == "NOOP")
vanilla_noop <- vanilla %>% filter(app == "NOOP")
pb_thumb <- pb %>% filter(app == "Thumbnail Maker")
vanilla_thumb <- vanilla %>% filter(app == "Thumbnail Maker")

p <- c("yellowgreen", "violetred4")
cOff <- p[1]
cOn <- p[2]
ggplot(rbind(pb, vanilla), aes(value, linetype=type, color=type)) +
  facet_wrap(~app, scales="free") +
  stat_ecdf(size=1.5) +
  theme_pubclean() +
  scale_color_manual(values=p) +
  labs(y = "ECDF", x="Tempo de Serviço (ms)", linetype="Técnica", color="Técnica") +
  theme(
    legend.position="bottom",
    panel.grid.major.x = element_line(colour = "darkgray", linetype = 3))
ggsave("service_time.png")

```

```{r}
# Ambos os csv's (Criu e NoCriu) possuem as seguintes métricas:
# MainEntry -- Timestamp em nanosegundos do momento em que a app entrou no código Main.
# MainExit -- Timestamp em nanosegundos do momento em que a app saiu do código Main.
# Read2Serve -- Timestamp em nanosegundos do momento em que a função da app começou a atender a requisição.
# RuntimeReadyTime -- Tempo em nanosegundos que levou para a função da app começar a atender a requisição.
# ServiceTime -- Tempo em nanosegundos que levou para a função da app começar a servir/computar a requisição.
# LatencyTime -- Tempo em nanosegundos que levou para a app responder a requisição.

# Porém, a execução sem criu (NoCriu) possui as seguintes métricas adicionais:

# LoadedClasses -- Quantidade de classes carregadas na função da app no momento da requisição
# FindingClassesTime -- Tempo em nanosegundos que a função da app passou apenas encontrando as classes, ou seja, o tempo de lê os dados do arquivo .class e criar o objeto Class<?>.
# CompilingClassesTime -- Tempo em nanosegundos que a função da app passou apenas criando as instâncias das classes pelo construtor de default (é sempre garantido que ele existe!).
# LoadClassesTotalTime -- Tempo em nanosegundos que a função da app passou lendo as entradas do jar da função sintética (o nome dos arquivos .class da função sintética gerada), carregando e compilando todas as classes.
# LoadingClassesOverheadTime -- Tempo em nanosegundos que durante o carregamento das classes a função da app não estava encontrando ou compilando classes, podemos interpretar como (LoadClassesTotalTime - FindingClassesTime - CompilingClassesTime).

require(dplyr)
require(ggplot2)
require(reshape)

read_service_time <- function(f) {
  df <- read.csv(f) 
  df <- data.frame(
    Complexity=df[df$Metric=="ServiceTime", ]$Loaded_Classes,
    Value=df[df$Metric=="ServiceTime", ]$KernelTime_NS+df[df$Metric=="RuntimeReadyTime", ]$KernelTime_NS)
  colnames(df) <- c("app", "value")
  df$value <- df$value / 10^6 
  df <- df %>% mutate(app = ifelse(app == "50", "Low", ifelse(app == 250, "Medium", "High")))
  return(df)
}
pb <- read_service_time("criu-nobpftrace-gc-warmup-noop-class-loader.csv")
pb$type <- "Prebaking"
vanilla <- read_service_time("nocriu-nobpftrace-nogc-nowarmup-noop-class-loader.csv")
vanilla$type <- "Vanilla"


p <- c("yellowgreen", "violetred4")
ggplot(data.frame(value=vanilla$value/pb$value, app=pb$app), aes(x=app, value)) +
  geom_bar(position="dodge", stat = "identity") +
  theme_pubclean() +
  scale_color_manual(values=p) +
  labs(y = "Improvement (times)", x="Complexity") +
  scale_x_discrete(limits=c("Low", "Medium", "High")) +
  theme(
    legend.position="bottom",
    panel.grid.major.x = element_line(colour = "darkgray", linetype = 3))
```
