/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GC */

#ifndef _Included_GC
#define _Included_GC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GC
 * Method:    force
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GC_force
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
