#!/bin/sh

set -euo pipefail

ROOT_DIR=$(pwd)

# Initialization - load function handler
# LAMBDA TASK ROOT - directory with CRIU dump files
cd $LAMBDA_TASK_ROOT

# CRIU Restore
LD_PRELOAD=${ROOT_DIR}/libprotobuf-c.so.1 $ROOT_DIR/criu restore -d -v3 -o restore.log

# Processing
while true
do
  sleep 1000
done